canton.participants.b-validator-1.ledger-api {
  auth-services = [{
    type = jwt-jwks
    url = ${AUTH_B_VALIDATOR_1_JWK_SET_URL}
    target-audience = ${AUTH_B_VALIDATOR_1_AUDIENCE}
  }]
  user-management-service.additional-admin-user-id=${AUTH_B_VALIDATOR_1_VALIDATOR_USER_ID}
}