canton.participants.d-validator-1.ledger-api {
  auth-services = [{
    type = jwt-jwks
    url = ${AUTH_D_VALIDATOR_1_JWK_SET_URL}
    target-audience = ${AUTH_D_VALIDATOR_1_AUDIENCE}
  }]
  user-management-service.additional-admin-user-id=${AUTH_D_VALIDATOR_1_VALIDATOR_USER_ID}
}
