canton.features.enable-testing-commands = yes

include file("/app/a-validator-1/on/app.conf")
include file("/app/a-validator-1/on/app-auth.conf")
include file("/app/b-validator-1/on/app.conf")
include file("/app/b-validator-1/on/app-auth.conf")
include file("/app/sv-validator-1/on/app.conf")
include file("/app/sv-validator-1/on/app-auth.conf")
