#!/bin/bash
# Copyright (c) 2026 Peaceful Studio OÜ
# SPDX-License-Identifier: Apache-2.0

set -eo pipefail

source /app/utils.sh

if [ "$AUTH_MODE" = "oauth2" ]; then
  export D_VALIDATOR_1_PARTICIPANT_ADMIN_TOKEN=$(get_admin_token $AUTH_D_VALIDATOR_1_VALIDATOR_CLIENT_SECRET $AUTH_D_VALIDATOR_1_VALIDATOR_CLIENT_ID $AUTH_D_VALIDATOR_1_TOKEN_URL)
  export D_VALIDATOR_1_PARTY=$(get_user_party "$D_VALIDATOR_1_PARTICIPANT_ADMIN_TOKEN" $AUTH_D_VALIDATOR_1_VALIDATOR_USER_ID "canton:14${PARTICIPANT_JSON_API_PORT_SUFFIX}")
  export D_VALIDATOR_1_WALLET_ADMIN_TOKEN=$(get_user_token $AUTH_D_VALIDATOR_1_WALLET_ADMIN_USER_NAME $AUTH_D_VALIDATOR_1_WALLET_ADMIN_USER_PASSWORD $AUTH_D_VALIDATOR_1_AUTO_CONFIG_CLIENT_ID $AUTH_D_VALIDATOR_1_TOKEN_URL)
  export DSO_PARTY=$(get_dso_party_id "$D_VALIDATOR_1_WALLET_ADMIN_TOKEN" "splice:14${VALIDATOR_ADMIN_API_PORT_SUFFIX}")


  if [ "$DO_INIT" == "true" ] && [ ! -f /tmp/d-validator-1-init-user-cleanup ]; then
    update_user "$D_VALIDATOR_1_PARTICIPANT_ADMIN_TOKEN" $AUTH_D_VALIDATOR_1_WALLET_ADMIN_USER_ID $AUTH_D_VALIDATOR_1_WALLET_ADMIN_USER_NAME $D_VALIDATOR_1_PARTY "canton:14${PARTICIPANT_JSON_API_PORT_SUFFIX}"
    update_user "$D_VALIDATOR_1_PARTICIPANT_ADMIN_TOKEN" $AUTH_D_VALIDATOR_1_VALIDATOR_USER_ID $AUTH_D_VALIDATOR_1_VALIDATOR_USER_NAME $D_VALIDATOR_1_PARTY "canton:14${PARTICIPANT_JSON_API_PORT_SUFFIX}"

    delete_user "$D_VALIDATOR_1_PARTICIPANT_ADMIN_TOKEN" participant_admin "canton:14${PARTICIPANT_JSON_API_PORT_SUFFIX}"
    touch /tmp/d-validator-1-init-user-cleanup
  fi

else
  export D_VALIDATOR_1_PARTICIPANT_ADMIN_TOKEN=$(generate_jwt "$AUTH_D_VALIDATOR_1_VALIDATOR_USER_NAME" "$AUTH_D_VALIDATOR_1_AUDIENCE")
  export D_VALIDATOR_1_PARTY=$(get_user_party "$D_VALIDATOR_1_PARTICIPANT_ADMIN_TOKEN" $AUTH_D_VALIDATOR_1_VALIDATOR_USER_NAME "canton:14${PARTICIPANT_JSON_API_PORT_SUFFIX}")
  export D_VALIDATOR_1_WALLET_ADMIN_TOKEN=$(generate_jwt "$AUTH_D_VALIDATOR_1_WALLET_ADMIN_USER_NAME" "$AUTH_D_VALIDATOR_1_AUDIENCE")
  export DSO_PARTY=$(get_dso_party_id "$D_VALIDATOR_1_WALLET_ADMIN_TOKEN" "splice:14${VALIDATOR_ADMIN_API_PORT_SUFFIX}")

  if [ "$DO_INIT" == "true" ] && [ ! -f /tmp/d-validator-1-init-user-cleanup ]; then
    delete_user "$D_VALIDATOR_1_PARTICIPANT_ADMIN_TOKEN" participant_admin "canton:14${PARTICIPANT_JSON_API_PORT_SUFFIX}"
    touch /tmp/d-validator-1-init-user-cleanup
  fi
fi
