canton.remote-participants.sv-validator-1 {
  ledger-api {
    address = canton
    port = 10${PARTICIPANT_LEDGER_API_PORT_SUFFIX}
  }
  admin-api {
    address = canton
    port = 10${PARTICIPANT_ADMIN_API_PORT_SUFFIX}
  }
}
