# Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
---
x-vars:
  a-validator-1-auth-env: &a-validator-1-auth-env
    path: ${A_VALIDATOR_1_AUTH_ENV}
    required: false

  b-validator-1-auth-env: &b-validator-1-auth-env
    path: ${B_VALIDATOR_1_AUTH_ENV}
    required: false

  c-validator-1-auth-env: &c-validator-1-auth-env
    path: ${C_VALIDATOR_1_AUTH_ENV}
    required: false

  d-validator-1-auth-env: &d-validator-1-auth-env
    path: ${D_VALIDATOR_1_AUTH_ENV}
    required: false

volumes:
  onboarding:

services:
  splice-onboarding:
    build: ${MODULES_DIR}/splice-onboarding/docker
    container_name: splice-onboarding
    env_file:
      - ${LOCALNET_ENV_DIR}/common.env
      - *a-validator-1-auth-env
      - *b-validator-1-auth-env
      - *c-validator-1-auth-env
      - *d-validator-1-auth-env
    environment:
      - AUTH_MODE=${AUTH_MODE}
      - TEST_MODE=${TEST_MODE}
    volumes:
      - ${MODULES_DIR}/splice-onboarding/docker/entrypoint.sh:/entrypoint.sh
      - ${MODULES_DIR}/splice-onboarding/docker/health-check.sh:/app/health-check.sh
      - ${MODULES_DIR}/splice-onboarding/docker/utils.sh:/app/utils.sh
      - ${MODULES_DIR}/splice-onboarding/docker/a-validator-1.sh:/app/a-validator-1-auth.sh
      - ${MODULES_DIR}/splice-onboarding/docker/b-validator-1.sh:/app/b-validator-1-auth.sh
      - ${MODULES_DIR}/splice-onboarding/docker/c-validator-1.sh:/app/c-validator-1-auth.sh
      - ${MODULES_DIR}/splice-onboarding/docker/d-validator-1.sh:/app/d-validator-1-auth.sh
      - onboarding:/onboarding
    healthcheck:
      test: ["CMD", "bash", "/app/health-check.sh"]
      interval: 5s
      timeout: 100s
      retries: 1000
      start_period: 300s
    entrypoint: [ "/entrypoint.sh", "--init" ]
    stdin_open: true
    tty: true
    depends_on:
      splice:
        condition: service_healthy
