# Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

---
# Since a-validator-1, b-validator-1, c-validator-1, and d-validator-1 profiles are optional, we relax the environment file requirements to avoid Docker errors when a profile is disabled.
x-vars:
  a-validator-1-wallet-auth-env: &a-validator-1-wallet-auth-env
    path: ${MODULES_DIR}/keycloak/env/a-validator-1/${A_VALIDATOR_1_PROFILE}/wallet.oauth2.env
    required: false

  b-validator-1-wallet-auth-env: &b-validator-1-wallet-auth-env
    path: ${MODULES_DIR}/keycloak/env/b-validator-1/${B_VALIDATOR_1_PROFILE}/wallet.oauth2.env
    required: false

  c-validator-1-wallet-auth-env: &c-validator-1-wallet-auth-env
    path: ${MODULES_DIR}/keycloak/env/c-validator-1/${C_VALIDATOR_1_PROFILE}/wallet.oauth2.env
    required: false

  a-validator-1-ans-auth-env: &a-validator-1-ans-auth-env
    path: ${MODULES_DIR}/keycloak/env/a-validator-1/${A_VALIDATOR_1_PROFILE}/ans.oauth2.env
    required: false

  b-validator-1-ans-auth-env: &b-validator-1-ans-auth-env
    path: ${MODULES_DIR}/keycloak/env/b-validator-1/${B_VALIDATOR_1_PROFILE}/ans.oauth2.env
    required: false

  c-validator-1-ans-auth-env: &c-validator-1-ans-auth-env
    path: ${MODULES_DIR}/keycloak/env/c-validator-1/${C_VALIDATOR_1_PROFILE}/ans.oauth2.env
    required: false

  d-validator-1-wallet-auth-env: &d-validator-1-wallet-auth-env
    path: ${MODULES_DIR}/keycloak/env/d-validator-1/${D_VALIDATOR_1_PROFILE}/wallet.oauth2.env
    required: false

  d-validator-1-ans-auth-env: &d-validator-1-ans-auth-env
    path: ${MODULES_DIR}/keycloak/env/d-validator-1/${D_VALIDATOR_1_PROFILE}/ans.oauth2.env
    required: false

services:
  nginx-keycloak:
    image: "nginx:${NGINX_VERSION}"
    container_name: nginx-keycloak
    volumes:
      - ${MODULES_DIR}/keycloak/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8082:8082"
    depends_on:
      keycloak:
        condition: service_healthy
    # Workaround limitation of using localhost subdomains in QS. It is used only in backend-service
    # to configure frontend facing client otherwise the configuration would be quite difficult.
    networks:
      default:
        aliases:
          - keycloak.localhost
    profiles:
      - keycloak

  keycloak:
    image: "${KEYCLOAK_IMAGE}:${KEYCLOAK_VERSION}"
    container_name: keycloak
    volumes:
      - ${MODULES_DIR}/keycloak/conf/data:/opt/keycloak/data/import
    env_file:
      - ${LOCALNET_ENV_DIR}/common.env
      - ${MODULES_DIR}/keycloak/env/keycloak.env
    command: ["start-dev", "--import-realm", "--http-port=8082", "--health-enabled=true", "--hostname-strict=false", "--proxy-headers=forwarded"]
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/9000 && echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost:9000\r\nConnection: close\r\n\r\n' >&3 && cat <&3 | grep -q '200 OK'"]
      interval: 30s
      timeout: 10s
      retries: 50
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - keycloak

  postgres:
    environment:
      - CREATE_DATABASE_keycloakdb=keycloakdb

  canton:
    depends_on:
       keycloak:
         condition: service_healthy
    volumes:
      - ${MODULES_DIR}/keycloak/conf/canton/a-validator-1.conf:/app/a-validator-1/${A_VALIDATOR_1_PROFILE}/app-auth.conf
      - ${MODULES_DIR}/keycloak/conf/canton/b-validator-1.conf:/app/b-validator-1/${B_VALIDATOR_1_PROFILE}/app-auth.conf
      - ${MODULES_DIR}/keycloak/conf/canton/c-validator-1.conf:/app/c-validator-1/${C_VALIDATOR_1_PROFILE}/app-auth.conf
      - ${MODULES_DIR}/keycloak/conf/canton/d-validator-1.conf:/app/d-validator-1/${D_VALIDATOR_1_PROFILE}/app-auth.conf

  splice:
    depends_on:
      keycloak:
        condition: service_healthy
    volumes:
      - ${MODULES_DIR}/keycloak/conf/splice/a-validator-1.conf:/app/a-validator-1/${A_VALIDATOR_1_PROFILE}/app-auth.conf
      - ${MODULES_DIR}/keycloak/conf/splice/b-validator-1.conf:/app/b-validator-1/${B_VALIDATOR_1_PROFILE}/app-auth.conf
      - ${MODULES_DIR}/keycloak/conf/splice/c-validator-1.conf:/app/c-validator-1/${C_VALIDATOR_1_PROFILE}/app-auth.conf
      - ${MODULES_DIR}/keycloak/conf/splice/d-validator-1.conf:/app/d-validator-1/${D_VALIDATOR_1_PROFILE}/app-auth.conf

  ans-web-ui-a-validator-1:
    env_file:
      - *a-validator-1-ans-auth-env

  ans-web-ui-b-validator-1:
    env_file:
      - *b-validator-1-ans-auth-env

  ans-web-ui-c-validator-1:
    env_file:
      - *c-validator-1-ans-auth-env

  ans-web-ui-d-validator-1:
    env_file:
      - *d-validator-1-ans-auth-env

  wallet-web-ui-a-validator-1:
    env_file:
      - *a-validator-1-wallet-auth-env

  wallet-web-ui-b-validator-1:
    env_file:
      - *b-validator-1-wallet-auth-env

  wallet-web-ui-c-validator-1:
    env_file:
      - *c-validator-1-wallet-auth-env

  wallet-web-ui-d-validator-1:
    env_file:
      - *d-validator-1-wallet-auth-env

  console:
    volumes:
      - ${MODULES_DIR}/keycloak/docker/console/a-validator-1.sh:/app/pre-startup/${A_VALIDATOR_1_PROFILE}/a-validator-1.sh
      - ${MODULES_DIR}/keycloak/docker/console/b-validator-1.sh:/app/pre-startup/${B_VALIDATOR_1_PROFILE}/b-validator-1.sh
      - ${MODULES_DIR}/keycloak/docker/console/c-validator-1.sh:/app/pre-startup/${C_VALIDATOR_1_PROFILE}/c-validator-1.sh
      - ${MODULES_DIR}/keycloak/docker/console/d-validator-1.sh:/app/pre-startup/${D_VALIDATOR_1_PROFILE}/d-validator-1.sh
