canton.validator-apps.c-validator-1-backend = ${_validator_backend} {
  onboarding.secret = ${?C_VALIDATOR_1_VALIDATOR_ONBOARDING_SECRET}
  storage.config.properties.databaseName = validator-c-validator-1
  admin-api.port = 13${VALIDATOR_ADMIN_API_PORT_SUFFIX}
  participant-client {
    admin-api.port = 13${PARTICIPANT_ADMIN_API_PORT_SUFFIX}
    ledger-api.client-config.port = 13${PARTICIPANT_LEDGER_API_PORT_SUFFIX}
  }
  validator-party-hint = ${C_VALIDATOR_1_PARTY_HINT}

  domains.global.buy-extra-traffic {
    min-topup-interval = ${MIN_TRAFFIC_TOPUP_INTERVAL}
    target-throughput = ${TARGET_TRAFFIC_THROUGHPUT}
  }
}
