canton.validator-apps.d-validator-1-backend = ${_validator_backend} {
  onboarding.secret = ${?D_VALIDATOR_1_VALIDATOR_ONBOARDING_SECRET}
  storage.config.properties.databaseName = validator-d-validator-1
  admin-api.port = 14${VALIDATOR_ADMIN_API_PORT_SUFFIX}
  participant-client {
    admin-api.port = 14${PARTICIPANT_ADMIN_API_PORT_SUFFIX}
    ledger-api.client-config.port = 14${PARTICIPANT_LEDGER_API_PORT_SUFFIX}
  }
  validator-party-hint = ${D_VALIDATOR_1_PARTY_HINT}

  domains.global.buy-extra-traffic {
    min-topup-interval = ${MIN_TRAFFIC_TOPUP_INTERVAL}
    target-throughput = ${TARGET_TRAFFIC_THROUGHPUT}
  }
}
