canton.participants.d-validator-1 {
  ledger-api{
    auth-services = [{
      type = unsafe-jwt-hmac-256
      target-audience = ${AUTH_D_VALIDATOR_1_AUDIENCE}
      secret = "unsafe"
    }]

    user-management-service.additional-admin-user-id = ${AUTH_D_VALIDATOR_1_VALIDATOR_USER_NAME}
  }
}
