canton.participants.d-validator-1 = ${_participant} {
  storage.config.properties.databaseName = participant-d-validator-1
  monitoring {
    http-health-server.port = 14${CANTON_HTTP_HEALTHCHECK_PORT_SUFFIX}
    grpc-health-server.port= 14${CANTON_GRPC_HEALTHCHECK_PORT_SUFFIX}
  }
  http-ledger-api.port = 14${PARTICIPANT_JSON_API_PORT_SUFFIX}
  admin-api.port = 14${PARTICIPANT_ADMIN_API_PORT_SUFFIX}
  ledger-api.port = 14${PARTICIPANT_LEDGER_API_PORT_SUFFIX}
  parameters.alpha-version-support = yes
}
