canton.remote-participants.a-validator-1 {
  ledger-api {
    address = canton
    port = 11${PARTICIPANT_LEDGER_API_PORT_SUFFIX}
  }

  admin-api {
    address = canton
    port = 11${PARTICIPANT_ADMIN_API_PORT_SUFFIX}
  }
}

canton.remote-sequencers.app-sequencer {
  public-api {
    address = canton
    port = 5018
  }

  admin-api {
    address = canton
    port = 5019
  }
}

canton.remote-mediators.app-mediator {

  admin-api {
    address = canton
    port = 5017
  }
}
