canton.validator-apps.b-validator-1-backend {
  participant-client.ledger-api.auth-config = {
    type = "self-signed"
    user = ${AUTH_B_VALIDATOR_1_VALIDATOR_USER_NAME}
    audience = ${AUTH_B_VALIDATOR_1_AUDIENCE}
    secret = "unsafe"
  }

  auth = {
    algorithm = "hs-256-unsafe"
    audience = ${AUTH_B_VALIDATOR_1_AUDIENCE}
    secret = "unsafe"
  }

  ledger-api-user = ${AUTH_B_VALIDATOR_1_VALIDATOR_USER_NAME}
  validator-wallet-users.0 = ${AUTH_B_VALIDATOR_1_WALLET_ADMIN_USER_NAME}

}
