# Copyright (c) 2026 Peaceful Studio OÜ
# SPDX-License-Identifier: Apache-2.0

name: Go CI

on:
  push:
    branches: [dev]
    paths:
      - 'go/**'
      - 'cli/**'
      - '.github/workflows/go-ci.yaml'
  pull_request:
    branches: [dev]
    paths:
      - 'go/**'
      - 'cli/**'
      - '.github/workflows/go-ci.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  go-ci:
    uses: peacefulstudio/github-actions/.github/workflows/go-ci.yaml@v1
    permissions:
      contents: read
      pull-requests: write
    with:
      go-version: '1.26'
