# Copyright (c) 2026 Peaceful Studio OÜ
# SPDX-License-Identifier: Apache-2.0

name: terraform-ci

on:
  push:
    branches: [dev]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-ci.yaml'
  pull_request:
    branches: [dev]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-ci.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  terraform-ci:
    uses: peacefulstudio/github-actions/.github/workflows/terraform-ci.yaml@v1
    permissions:
      contents: read
      pull-requests: write
